### ISSUE TITLE
Would be great to have positional arguments for queries and number of downloads

### ISSUE THREAD

**Issue by AbhinavMir** [AbhinavMir/tasveer#1]
Presently we have to manually enter the arguments, I would like to replace that by positional (or even Keyword) arguments.

**Comment by steeeveee8** [comment]
I'd love to help implement this! I can send over a pull request.

**Comment by AbhinavMir** [comment]
@steveyackey Happy New Year Steve, and I am accepting your pull request :)
Thank you so much :)
Will release to Pip once two more issues get solved. 
I am so swamped working on this book, don't get time :(

Could you also add a small documentation or sent it over to me at contact@abhinavmir.tech ?

**Comment by steeeveee8** [comment]
Thanks so much! I can definitely do that! Hope you’re having a great new year!
