### ISSUE TITLE
Please add a feature to decide frame width and height before download

### ISSUE THREAD

**Issue by ritumbhara** [AbhinavMir/tasveer#6]

**Comment by AbhinavMir** [comment]
Thanks for raising an issue, I will add this to the readme!

**Comment by Mansi145** [comment]
Can I work on this issue? I did some prior research regarding this issue and I think I can fix this.

**Comment by AbhinavMir** [comment]
Sure, please add yourself to the Slack from readme if you need any help from the community.

**Comment by AbhinavMir** [comment]
Solved by Mansi
